### ISSUE TITLE
How to use this with IP spoofing easily?

### ISSUE THREAD

**Issue by ghost** [smok-serwis/siege-engine#3]

**Comment by piotrmaslanka** [comment]
You can install yourself the version 1.6 via pip install siege-engine==1.6
. It has IP spoofing added.

However, it will require scapy installed, or a C compiler to compile the
necessary extensions.

Best regards,
Piotr

niedz., 27 lut 2022 o 14:24 Joel Derbyshire ***@***.***>
napisał(a):

**Comment by ghost** [comment]
Thank you.
